---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/index.md
  label: Home
- type: document
  path: content/about.md
  label: About
- type: document
  path: content/contact.md
  label: Contact
- type: heading
  label: Collections
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*.md"
- type: directory
  path: content/case-studies
  label: Case Studies
  create: all
  match: "**/*.md"
- type: directory
  path: content/services
  label: Services
  create: all
  match: "**/*.md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
