---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Primary Pages
- type: document
  path: content/index.md
  label: Home
- type: document
  path: content/about.md
  label: About
- type: document
  path: content/contact.md
  label: Contact
- type: heading
  label: Collections
- type: directory
  path: content
  label: All Pages
  create: all
  match: "**/*.md"
  exclude: articles/*.md
  templates:
  - page-builder
- type: directory
  path: content/articles
  label: Blog
  create: all
  match: "**/*.md"
- type: heading
  label: Site
- type: document
  label: Editor Defaults
  path: data/editor.json
upload_dir: static/images
public_path: "/static/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
