---
new_page_extension: md
auto_deploy: false
admin_path: studio
webhook_url: 
sections:
- type: heading
  label: Primary Pages
- type: document
  path: content/index.md
  label: Home
- type: document
  path: content/about.md
  label: About
- type: document
  path: content/contact.md
  label: Contact
- type: document
  path: content/styleguide.md
  label: Style Guide
- type: heading
  label: Collections
- type: directory
  path: content
  label: All Pages
  create: all
  match: "**/*.md"
  exclude: articles/*.md, globals/*.md
  templates:
  - page-builder
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*.md"
- type: directory
  path: content/masters
  label: Master Templates
  create: documents
  match: "**/*.md"
  templates:
  - global-builder
- type: heading
  label: Site Settings
- type: document
  path: data/site.json
  label: Configuration
- type: document
  path: data/navigation.json
  label: Menus
- type: document
  path: data/editor.json
  label: Appearance
upload_dir: static/images
public_path: static/images
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
