---
label: Utility - SEO
hide_body: true
fields:
- name: hidden
  type: boolean
  label: Hidden
  description: Disallow being indexed by search engines
- name: title
  type: text
  config:
    required: false
  label: Meta Title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Meta Description
